imports_granularity = "Crate"
group_imports = "One"
imports_layout = "HorizontalVertical"
edition = "2021"

comment_width = 100
max_width = 100
newline_style = "Unix"
#normalize_comments = true
reorder_imports = true
wrap_comments = true
unstable_features = true
